### ISSUE TITLE
Autocomplete function name capitalizes (first letter) to match imported module name

### ISSUE THREAD

**Issue by ltfschoen** [joneshf/sublime-purescript#1]
After importing a module with `Data.Trace`, when the user tries to enter the main program defined as a function application using the `trace` function, the autocomplete selection provided only includes the a capitalized `Trace` option (due to that module being previously imported), instead of a lowercase `trace` option from the drop-down for the function. If the user incorrectly chooses the capitalized option, the PureScript program will not compile, as function names must be lowercase.
See screenshot below of the single autocomplete drop-down item shown when the first few letters of the function name are typed.
![screen shot 2015-01-05 at 11 35 51 pm](https://cloud.githubusercontent.com/assets/6226175/5613142/aca39ce6-9533-11e4-8a43-f42cc17257e0.png)

**Comment by joneshf** [comment]
I apologize, but there's nothing like intellisense or `ModuleInspector` like in `SublimeHaskell`. So, if you import something in a ps file, it won't also import the functions from that module as completions into sublime. The completions here are just standard sublime stuff. 

It seems like quite a bit of work to get that working. It'd have to find the module, then load the functions, and make them available as completions. Since we'd have to either make some rather broad assumptions about where to find modules or we'd need to deal with per project settings (as there's no global repo on a user's computer of ps packages) it seems like quite a bit of work to get right.

If you have any suggestions here feel free to give them. I'd like this to work as well, just seems like a lot of work.

**Comment by joneshf** [comment]
Closing for now. If anything changes, feel free to open.
